/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felipe
 */
public class AdministradorPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public AdministradorPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSupP = new javax.swing.JPanel();
        AdministradorL = new javax.swing.JLabel();
        cerrarB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        registradoL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();
        accionesL = new javax.swing.JLabel();
        administrarUsuariosP = new javax.swing.JPanel();
        crearB = new javax.swing.JButton();
        consultarB = new javax.swing.JButton();
        modificarB = new javax.swing.JButton();
        eliminarB = new javax.swing.JButton();
        panelInfP = new javax.swing.JPanel();

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        AdministradorL.setText("SIAC - Administrador");
        panelSupP.add(AdministradorL);
        AdministradorL.setBounds(6, 7, 135, 16);

        cerrarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cerrarB.setText("X");
        cerrarB.setBorderPainted(false);
        cerrarB.setContentAreaFilled(false);
        cerrarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cerrarB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelSupP.add(cerrarB);
        cerrarB.setBounds(450, 0, 55, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User.png"))); // NOI18N

        bienvenidoL.setText("Bienvenido de nuevo: Administrador");

        registradoL.setText("Esta registrado en la empresa: Empresa");

        rolL.setText("Su rol en esta empresa es: Administrador");

        accionesL.setText("Las acciones que puede realizar son:");

        administrarUsuariosP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Usuarios de Empresa"));

        crearB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Crear.png"))); // NOI18N
        crearB.setText("Crear");
        crearB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        consultarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarB.setText("Consultar");
        consultarB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        modificarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarB.setText("Modificar");
        modificarB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        eliminarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarB.setText("Eliminar");
        eliminarB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout administrarUsuariosPLayout = new org.jdesktop.layout.GroupLayout(administrarUsuariosP);
        administrarUsuariosP.setLayout(administrarUsuariosPLayout);
        administrarUsuariosPLayout.setHorizontalGroup(
            administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarUsuariosPLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(crearB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(modificarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 72, Short.MAX_VALUE)
                .add(administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(consultarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(eliminarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(38, 38, 38))
        );
        administrarUsuariosPLayout.setVerticalGroup(
            administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarUsuariosPLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crearB)
                    .add(consultarB))
                .add(30, 30, 30)
                .add(administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarB)
                    .add(eliminarB))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jLabel2)
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, registradoL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bienvenidoL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, rolL)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(accionesL)))
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .add(administrarUsuariosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18))
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(bienvenidoL)
                        .add(18, 18, 18)
                        .add(registradoL)
                        .add(18, 18, 18)
                        .add(rolL)))
                .add(29, 29, 29)
                .add(accionesL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(administrarUsuariosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministradorL;
    private javax.swing.JLabel accionesL;
    private javax.swing.JPanel administrarUsuariosP;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JButton cerrarB;
    private javax.swing.JButton consultarB;
    private javax.swing.JButton crearB;
    private javax.swing.JButton eliminarB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton modificarB;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JLabel registradoL;
    private javax.swing.JLabel rolL;
    // End of variables declaration//GEN-END:variables
}
