/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felipe
 */
public class ConsultarPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public ConsultarPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSupP = new javax.swing.JPanel();
        AdministradorL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        registradoL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();
        accionesL = new javax.swing.JLabel();
        consultarUsuariosP = new javax.swing.JPanel();
        consultarB = new javax.swing.JButton();
        panelInfP = new javax.swing.JPanel();

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        AdministradorL.setText("SIAC - Usuario");
        panelSupP.add(AdministradorL);
        AdministradorL.setBounds(6, 7, 93, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User.png"))); // NOI18N

        bienvenidoL.setText("Bienvenido de nuevo: Usuario");

        registradoL.setText("Esta registrado en la empresa: Empresa");

        rolL.setText("Su rol en esta empresa es: Usuario");

        accionesL.setText("Las acciones que puede realizar son:");

        consultarUsuariosP.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Usuarios de Empresa"));

        consultarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarB.setText("Consultar");
        consultarB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout consultarUsuariosPLayout = new org.jdesktop.layout.GroupLayout(consultarUsuariosP);
        consultarUsuariosP.setLayout(consultarUsuariosPLayout);
        consultarUsuariosPLayout.setHorizontalGroup(
            consultarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(consultarUsuariosPLayout.createSequentialGroup()
                .add(140, 140, 140)
                .add(consultarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        consultarUsuariosPLayout.setVerticalGroup(
            consultarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(consultarUsuariosPLayout.createSequentialGroup()
                .addContainerGap()
                .add(consultarB)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jLabel2)
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, registradoL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bienvenidoL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, rolL)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(accionesL)))
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .add(consultarUsuariosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18))
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(bienvenidoL)
                        .add(18, 18, 18)
                        .add(registradoL)
                        .add(18, 18, 18)
                        .add(rolL)))
                .add(29, 29, 29)
                .add(accionesL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(consultarUsuariosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministradorL;
    private javax.swing.JLabel accionesL;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JButton consultarB;
    private javax.swing.JPanel consultarUsuariosP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JLabel registradoL;
    private javax.swing.JLabel rolL;
    // End of variables declaration//GEN-END:variables
}
