package view;

import controller.ConsultarAdministradorController;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Felipe
 */
public class ConsultarAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public ConsultarAdministrador() {
        initComponents();
    }

    public JTable getUsuarioT() {
        return usuarioT;
    }

    public void setUsuarioT(JTable usuarioT) {
        this.usuarioT = usuarioT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaBG = new javax.swing.ButtonGroup();
        consultaUsuarioP = new javax.swing.JPanel();
        dniL = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        dniTF = new javax.swing.JTextField();
        nombreDeUsuarioL = new javax.swing.JLabel();
        nombreDeUsuarioTF = new javax.swing.JTextField();
        correoL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();
        correoTF = new javax.swing.JTextField();
        atrasB = new javax.swing.JButton();
        rolTF = new javax.swing.JTextField();
        bienvenidoL = new javax.swing.JLabel();
        dniRB = new javax.swing.JRadioButton();
        nombreRB = new javax.swing.JRadioButton();
        buscarTF = new javax.swing.JTextField();
        buscarB = new javax.swing.JButton();
        usuarioSP = new javax.swing.JScrollPane();
        usuarioT = new javax.swing.JTable();
        cancelarB = new javax.swing.JButton();
        verInformacionB = new javax.swing.JButton();

        dniL.setText("DNI:");

        nombreL.setText("Nombre:");

        nombreTF.setEditable(false);

        dniTF.setEditable(false);

        nombreDeUsuarioL.setText("Nombre de usuario:");

        nombreDeUsuarioTF.setEditable(false);

        correoL.setText("Correo:");

        rolL.setText("Rol:");

        correoTF.setEditable(false);

        atrasB.setText("Atrás");
        atrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBActionPerformed(evt);
            }
        });

        rolTF.setEditable(false);

        org.jdesktop.layout.GroupLayout consultaUsuarioPLayout = new org.jdesktop.layout.GroupLayout(consultaUsuarioP);
        consultaUsuarioP.setLayout(consultaUsuarioPLayout);
        consultaUsuarioPLayout.setHorizontalGroup(
            consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, consultaUsuarioPLayout.createSequentialGroup()
                .addContainerGap()
                .add(consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dniL)
                    .add(nombreL)
                    .add(nombreDeUsuarioL)
                    .add(correoL)
                    .add(rolL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(correoTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rolTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nombreDeUsuarioTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nombreTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dniTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .add(consultaUsuarioPLayout.createSequentialGroup()
                .add(153, 153, 153)
                .add(atrasB)
                .add(0, 0, Short.MAX_VALUE))
        );
        consultaUsuarioPLayout.setVerticalGroup(
            consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(consultaUsuarioPLayout.createSequentialGroup()
                .addContainerGap()
                .add(consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dniTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dniL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nombreL))
                .add(8, 8, 8)
                .add(consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreDeUsuarioTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nombreDeUsuarioL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(correoTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(correoL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(consultaUsuarioPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rolTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rolL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(atrasB)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(463, 431));

        bienvenidoL.setText("Buscar por:");

        busquedaBG.add(dniRB);
        dniRB.setSelected(true);
        dniRB.setText("DNI");

        busquedaBG.add(nombreRB);
        nombreRB.setText("Nombre");

        buscarTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        buscarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buscarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        buscarB.setText("Buscar");
        buscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBActionPerformed(evt);
            }
        });

        usuarioT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Correo", "Rol", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usuarioSP.setViewportView(usuarioT);

        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });

        verInformacionB.setText("Ver información");
        verInformacionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInformacionBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(dniRB)
                                .add(18, 18, 18)
                                .add(nombreRB))
                            .add(bienvenidoL)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(verInformacionB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelarB))
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(buscarTF)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(buscarB))
                            .add(usuarioSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 523, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(bienvenidoL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dniRB)
                    .add(nombreRB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(usuarioSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(verInformacionB)
                    .add(cancelarB)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
        new ConsultarAdministradorController().buscar();
    }//GEN-LAST:event_buscarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        new ConsultarAdministradorController().cancelar();
    }//GEN-LAST:event_cancelarBActionPerformed

    private void verInformacionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInformacionBActionPerformed
        new ConsultarAdministradorController().mostrarUsuario();
    }//GEN-LAST:event_verInformacionBActionPerformed

    private void atrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBActionPerformed
        new ConsultarAdministradorController().consultarUsuario();
    }//GEN-LAST:event_atrasBActionPerformed

    public JTextField getBuscarTF() {
        return buscarTF;
    }

    public void setBuscarTF(JTextField buscarTF) {
        this.buscarTF = buscarTF;
    }

    public JRadioButton getDniRB() {
        return dniRB;
    }

    public void setDniRB(JRadioButton dniRB) {
        this.dniRB = dniRB;
    }

    public JTextField getCorreoTF() {
        return correoTF;
    }

    public JTextField getDniTF() {
        return dniTF;
    }

    public JTextField getNombreDeUsuarioTF() {
        return nombreDeUsuarioTF;
    }

    public JTextField getNombreTF() {
        return nombreTF;
    }

    public JTextField getRolTF() {
        return rolTF;
    }

    public JPanel getConsultaUsuarioP() {
        return consultaUsuarioP;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasB;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JButton buscarB;
    private static javax.swing.JTextField buscarTF;
    private javax.swing.ButtonGroup busquedaBG;
    private javax.swing.JButton cancelarB;
    private javax.swing.JPanel consultaUsuarioP;
    private javax.swing.JLabel correoL;
    private javax.swing.JTextField correoTF;
    private javax.swing.JLabel dniL;
    private static javax.swing.JRadioButton dniRB;
    private javax.swing.JTextField dniTF;
    private javax.swing.JLabel nombreDeUsuarioL;
    private javax.swing.JTextField nombreDeUsuarioTF;
    private javax.swing.JLabel nombreL;
    private javax.swing.JRadioButton nombreRB;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel rolL;
    private javax.swing.JTextField rolTF;
    private javax.swing.JScrollPane usuarioSP;
    private static javax.swing.JTable usuarioT;
    private javax.swing.JButton verInformacionB;
    // End of variables declaration//GEN-END:variables
}
