/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felipe
 */
public class ConsultarEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public ConsultarEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaBG = new javax.swing.ButtonGroup();
        ConsultaF = new javax.swing.JFrame();
        panelSupP1 = new javax.swing.JPanel();
        crearEmpresaL = new javax.swing.JLabel();
        panelInfP1 = new javax.swing.JPanel();
        atrasB = new javax.swing.JButton();
        nitL = new javax.swing.JLabel();
        nombreEmpresaL = new javax.swing.JLabel();
        nivelL = new javax.swing.JLabel();
        direccionL = new javax.swing.JLabel();
        telefonoL = new javax.swing.JLabel();
        nitTF = new javax.swing.JTextField();
        nombreEmpresaTF = new javax.swing.JTextField();
        nivelTF = new javax.swing.JTextField();
        direccionTF = new javax.swing.JTextField();
        telefonoTF = new javax.swing.JTextField();
        empresaL = new javax.swing.JLabel();
        panelSupP = new javax.swing.JPanel();
        AdministradorL = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        panelInfP = new javax.swing.JPanel();
        nitRB = new javax.swing.JRadioButton();
        nombreRB = new javax.swing.JRadioButton();
        buscarTF = new javax.swing.JTextField();
        buscarB = new javax.swing.JToggleButton();
        empresaSP = new javax.swing.JScrollPane();
        empresaT = new javax.swing.JTable();
        cancelarB = new javax.swing.JButton();
        verInformacionB = new javax.swing.JButton();

        panelSupP1.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP1.setLayout(null);

        crearEmpresaL.setText("SIAC - Empresa");
        panelSupP1.add(crearEmpresaL);
        crearEmpresaL.setBounds(6, 7, 170, 16);

        panelInfP1.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP1.setLayout(null);

        atrasB.setText("Atrás");

        nitL.setText("NIT: ");

        nombreEmpresaL.setText("Nombre:");

        nivelL.setText("Nivel:");

        direccionL.setText("Dirección:");

        telefonoL.setText("Teléfono:");

        nitTF.setText("000000000");
        nitTF.setEnabled(false);

        nombreEmpresaTF.setText("Nombre");
        nombreEmpresaTF.setEnabled(false);

        nivelTF.setText("Nivel");
        nivelTF.setEnabled(false);

        direccionTF.setText("Calle Falsa 123");
        direccionTF.setEnabled(false);

        telefonoTF.setEnabled(false);

        empresaL.setText("Empresa:");

        org.jdesktop.layout.GroupLayout ConsultaFLayout = new org.jdesktop.layout.GroupLayout(ConsultaF.getContentPane());
        ConsultaF.getContentPane().setLayout(ConsultaFLayout);
        ConsultaFLayout.setHorizontalGroup(
            ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ConsultaFLayout.createSequentialGroup()
                .addContainerGap()
                .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(nitL)
                        .add(empresaL))
                    .add(ConsultaFLayout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nivelL)
                            .add(nombreEmpresaL)
                            .add(direccionL)
                            .add(telefonoL))))
                .add(18, 18, 18)
                .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(telefonoTF)
                    .add(ConsultaFLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(nombreEmpresaTF)
                            .add(nitTF)
                            .add(nivelTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)))
                    .add(direccionTF))
                .add(15, 15, 15))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelInfP1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(ConsultaFLayout.createSequentialGroup()
                .add(161, 161, 161)
                .add(atrasB)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(panelSupP1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ConsultaFLayout.setVerticalGroup(
            ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ConsultaFLayout.createSequentialGroup()
                .add(panelSupP1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(empresaL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nitL)
                    .add(nitTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreEmpresaTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nombreEmpresaL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nivelTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nivelL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(direccionL)
                    .add(direccionTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ConsultaFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(telefonoTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(telefonoL))
                .add(24, 24, 24)
                .add(atrasB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelInfP1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        AdministradorL.setText("SIAC - Consultar Empresa");
        panelSupP.add(AdministradorL);
        AdministradorL.setBounds(6, 7, 170, 16);

        bienvenidoL.setText("Buscar por:");

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        nitRB.setText("NIT");

        busquedaBG.add(nombreRB);
        nombreRB.setText("Nombre");

        buscarTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        buscarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buscarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        buscarB.setText("Buscar");

        empresaT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIT", "Nombre", "Nivel", "Dirección", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empresaSP.setViewportView(empresaT);

        cancelarB.setText("Cancelar");

        verInformacionB.setText("Ver información");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cancelarB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(verInformacionB))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(nitRB)
                                .add(18, 18, 18)
                                .add(nombreRB))
                            .add(bienvenidoL)
                            .add(layout.createSequentialGroup()
                                .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(buscarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(empresaSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 520, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bienvenidoL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nitRB)
                    .add(nombreRB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(empresaSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB)
                    .add(verInformacionB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministradorL;
    private javax.swing.JFrame ConsultaF;
    private javax.swing.JButton atrasB;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JToggleButton buscarB;
    private javax.swing.JTextField buscarTF;
    private javax.swing.ButtonGroup busquedaBG;
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel crearEmpresaL;
    private javax.swing.JLabel direccionL;
    private javax.swing.JTextField direccionTF;
    private javax.swing.JLabel empresaL;
    private javax.swing.JScrollPane empresaSP;
    private javax.swing.JTable empresaT;
    private javax.swing.JLabel nitL;
    private javax.swing.JRadioButton nitRB;
    private javax.swing.JTextField nitTF;
    private javax.swing.JLabel nivelL;
    private javax.swing.JTextField nivelTF;
    private javax.swing.JLabel nombreEmpresaL;
    private javax.swing.JTextField nombreEmpresaTF;
    private javax.swing.JRadioButton nombreRB;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelInfP1;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JPanel panelSupP1;
    private javax.swing.JLabel telefonoL;
    private javax.swing.JTextField telefonoTF;
    private javax.swing.JButton verInformacionB;
    // End of variables declaration//GEN-END:variables
}
