/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginController;

/**
 *
 * @author Felipe
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioL = new javax.swing.JLabel();
        panelInfP = new javax.swing.JPanel();
        contrasenaOlvidadaB = new javax.swing.JButton();
        usuarioTF = new javax.swing.JTextField();
        contrasenaPF = new javax.swing.JPasswordField();
        iniciarSesionB = new javax.swing.JButton();
        logoL = new javax.swing.JLabel();
        contrasenaL = new javax.swing.JLabel();
        panelSupP = new javax.swing.JPanel();
        siacL = new javax.swing.JLabel();
        cerrarB = new javax.swing.JButton();

        usuarioL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        usuarioL.setText("Usuario:");
        usuarioL.setToolTipText("");

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));

        org.jdesktop.layout.GroupLayout panelInfPLayout = new org.jdesktop.layout.GroupLayout(panelInfP);
        panelInfP.setLayout(panelInfPLayout);
        panelInfPLayout.setHorizontalGroup(
            panelInfPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 361, Short.MAX_VALUE)
        );
        panelInfPLayout.setVerticalGroup(
            panelInfPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );

        contrasenaOlvidadaB.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        contrasenaOlvidadaB.setText("¿Has olvidado tu contraseña?");
        contrasenaOlvidadaB.setBorderPainted(false);
        contrasenaOlvidadaB.setContentAreaFilled(false);
        contrasenaOlvidadaB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contrasenaOlvidadaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaOlvidadaBActionPerformed(evt);
            }
        });

        usuarioTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        usuarioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTFActionPerformed(evt);
            }
        });

        contrasenaPF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        iniciarSesionB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        iniciarSesionB.setText("Iniciar Sesión");
        iniciarSesionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBActionPerformed(evt);
            }
        });

        logoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo.png"))); // NOI18N

        contrasenaL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        contrasenaL.setText("Contraseña:");
        contrasenaL.setToolTipText("");

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        siacL.setText("SIAC");
        panelSupP.add(siacL);
        siacL.setBounds(6, 7, 40, 14);

        cerrarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cerrarB.setText("X");
        cerrarB.setBorderPainted(false);
        cerrarB.setContentAreaFilled(false);
        cerrarB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrarB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cerrarB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cerrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBActionPerformed(evt);
            }
        });
        panelSupP.add(cerrarB);
        cerrarB.setBounds(310, 0, 55, 30);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(usuarioL)
                    .add(contrasenaL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(contrasenaPF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .add(usuarioTF))
                .add(21, 21, 21))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(contrasenaOlvidadaB)
                        .add(18, 18, 18)
                        .add(iniciarSesionB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(118, 118, 118)
                        .add(logoL)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(38, 38, 38)
                .add(logoL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usuarioTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(usuarioL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(contrasenaPF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(contrasenaL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(iniciarSesionB)
                    .add(contrasenaOlvidadaB))
                .add(18, 18, 18)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBActionPerformed
        LoginController.cerrar();
    }//GEN-LAST:event_cerrarBActionPerformed

    private void contrasenaOlvidadaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaOlvidadaBActionPerformed
        LoginController.mostrarRecuperarContrasena();
    }//GEN-LAST:event_contrasenaOlvidadaBActionPerformed

    private void usuarioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTFActionPerformed

    private void iniciarSesionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBActionPerformed
        LoginController.login();
    }//GEN-LAST:event_iniciarSesionBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarB;
    private javax.swing.JLabel contrasenaL;
    private javax.swing.JButton contrasenaOlvidadaB;
    public javax.swing.JPasswordField contrasenaPF;
    private javax.swing.JButton iniciarSesionB;
    private javax.swing.JLabel logoL;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JLabel siacL;
    private javax.swing.JLabel usuarioL;
    public javax.swing.JTextField usuarioTF;
    // End of variables declaration//GEN-END:variables
}
