/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felipe
 */
public class ModificarEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public ModificarEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaBG = new javax.swing.ButtonGroup();
        ModificarF = new javax.swing.JFrame();
        panelSupP2 = new javax.swing.JPanel();
        crearEmpresaL1 = new javax.swing.JLabel();
        panelInfP2 = new javax.swing.JPanel();
        cancelarB2 = new javax.swing.JButton();
        modificarUsuarioB = new javax.swing.JButton();
        nitL1 = new javax.swing.JLabel();
        nombreEmpresaL1 = new javax.swing.JLabel();
        nivelL1 = new javax.swing.JLabel();
        direccionL1 = new javax.swing.JLabel();
        telefonoL1 = new javax.swing.JLabel();
        nitTF1 = new javax.swing.JTextField();
        nombreEmpresaTF1 = new javax.swing.JTextField();
        nivelTF1 = new javax.swing.JTextField();
        direccionTF1 = new javax.swing.JTextField();
        telefonoTF1 = new javax.swing.JTextField();
        empresaL1 = new javax.swing.JLabel();
        panelSupP = new javax.swing.JPanel();
        modificarEmpresaL = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        panelInfP = new javax.swing.JPanel();
        nitRB = new javax.swing.JRadioButton();
        nombreRB = new javax.swing.JRadioButton();
        buscarTF = new javax.swing.JTextField();
        buscarB = new javax.swing.JToggleButton();
        empresaSP = new javax.swing.JScrollPane();
        empresaT = new javax.swing.JTable();
        cancelarB = new javax.swing.JButton();
        modificarB = new javax.swing.JButton();

        panelSupP2.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP2.setLayout(null);

        crearEmpresaL1.setText("SIAC - Modificar Empresa");
        panelSupP2.add(crearEmpresaL1);
        crearEmpresaL1.setBounds(6, 7, 170, 16);

        panelInfP2.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP2.setLayout(null);

        cancelarB2.setText("Cancelar");

        modificarUsuarioB.setText("Modificar Usuario");

        nitL1.setText("NIT: ");

        nombreEmpresaL1.setText("Nombre:");

        nivelL1.setText("Nivel:");

        direccionL1.setText("Dirección:");

        telefonoL1.setText("Teléfono:");

        nivelTF1.setText("Nivel");
        nivelTF1.setEnabled(false);

        empresaL1.setText("Empresa:");

        org.jdesktop.layout.GroupLayout ModificarFLayout = new org.jdesktop.layout.GroupLayout(ModificarF.getContentPane());
        ModificarF.getContentPane().setLayout(ModificarFLayout);
        ModificarFLayout.setHorizontalGroup(
            ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelInfP2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelSupP2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(ModificarFLayout.createSequentialGroup()
                .addContainerGap()
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ModificarFLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(telefonoL1)
                            .add(nombreEmpresaL1)
                            .add(nitL1)
                            .add(nivelL1)
                            .add(direccionL1))
                        .add(27, 27, 27)
                        .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nombreEmpresaTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nitTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nivelTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(direccionTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(telefonoTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(empresaL1))
                .addContainerGap(11, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, ModificarFLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cancelarB2)
                .add(18, 18, 18)
                .add(modificarUsuarioB)
                .add(25, 25, 25))
        );
        ModificarFLayout.setVerticalGroup(
            ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ModificarFLayout.createSequentialGroup()
                .add(panelSupP2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(empresaL1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nitL1)
                    .add(nitTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreEmpresaL1)
                    .add(nombreEmpresaTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nivelL1)
                    .add(nivelTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(direccionL1)
                    .add(direccionTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(telefonoL1)
                    .add(telefonoTF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB2)
                    .add(modificarUsuarioB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(panelInfP2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        modificarEmpresaL.setText("SIAC - Modificar Empresa");
        panelSupP.add(modificarEmpresaL);
        modificarEmpresaL.setBounds(6, 7, 170, 16);

        bienvenidoL.setText("Buscar por:");

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        nitRB.setText("NIT");

        busquedaBG.add(nombreRB);
        nombreRB.setText("Nombre");

        buscarTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        buscarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buscarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        buscarB.setText("Buscar");

        empresaT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIT", "Nombre", "Nivel", "Dirección", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empresaSP.setViewportView(empresaT);

        cancelarB.setText("Cancelar");

        modificarB.setText("Modificar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cancelarB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(modificarB))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(nitRB)
                                .add(18, 18, 18)
                                .add(nombreRB))
                            .add(bienvenidoL)
                            .add(layout.createSequentialGroup()
                                .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(buscarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(empresaSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 520, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bienvenidoL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nitRB)
                    .add(nombreRB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(empresaSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB)
                    .add(modificarB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ModificarF;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JToggleButton buscarB;
    private javax.swing.JTextField buscarTF;
    private javax.swing.ButtonGroup busquedaBG;
    private javax.swing.JButton cancelarB;
    private javax.swing.JButton cancelarB2;
    private javax.swing.JLabel crearEmpresaL1;
    private javax.swing.JLabel direccionL1;
    private javax.swing.JTextField direccionTF1;
    private javax.swing.JLabel empresaL1;
    private javax.swing.JScrollPane empresaSP;
    private javax.swing.JTable empresaT;
    private javax.swing.JButton modificarB;
    private javax.swing.JLabel modificarEmpresaL;
    private javax.swing.JButton modificarUsuarioB;
    private javax.swing.JLabel nitL1;
    private javax.swing.JRadioButton nitRB;
    private javax.swing.JTextField nitTF1;
    private javax.swing.JLabel nivelL1;
    private javax.swing.JTextField nivelTF1;
    private javax.swing.JLabel nombreEmpresaL1;
    private javax.swing.JTextField nombreEmpresaTF1;
    private javax.swing.JRadioButton nombreRB;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelInfP2;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JPanel panelSupP2;
    private javax.swing.JLabel telefonoL1;
    private javax.swing.JTextField telefonoTF1;
    // End of variables declaration//GEN-END:variables
}
