/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felipe
 */
public class ModificarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public ModificarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaBG = new javax.swing.ButtonGroup();
        ModificarF = new javax.swing.JFrame();
        panelSupP1 = new javax.swing.JPanel();
        modificarUsuarioL1 = new javax.swing.JLabel();
        panelInfP1 = new javax.swing.JPanel();
        dniL = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        dniTF = new javax.swing.JTextField();
        nombreDeUsuarioL = new javax.swing.JLabel();
        nombreDeUsuarioTF = new javax.swing.JTextField();
        contrasenaL = new javax.swing.JLabel();
        confirmarContrasenaL = new javax.swing.JLabel();
        correoL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();
        contrasenaPF = new javax.swing.JPasswordField();
        confirmarContrasenaPF = new javax.swing.JPasswordField();
        correoTF = new javax.swing.JTextField();
        rolCB = new javax.swing.JComboBox();
        cancelarB1 = new javax.swing.JButton();
        modificarB1 = new javax.swing.JButton();
        panelSupP = new javax.swing.JPanel();
        modificarUsuarioL = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        panelInfP = new javax.swing.JPanel();
        dniRB = new javax.swing.JRadioButton();
        nombreRB = new javax.swing.JRadioButton();
        buscarTF = new javax.swing.JTextField();
        buscarB = new javax.swing.JToggleButton();
        usuarioSP = new javax.swing.JScrollPane();
        usuarioT = new javax.swing.JTable();
        cancelarB = new javax.swing.JButton();
        modificarB = new javax.swing.JButton();

        panelSupP1.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP1.setLayout(null);

        modificarUsuarioL1.setText("SIAC - Modificar usuario");
        panelSupP1.add(modificarUsuarioL1);
        modificarUsuarioL1.setBounds(6, 7, 160, 16);

        panelInfP1.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP1.setLayout(null);

        dniL.setText("DNI:");

        nombreL.setText("Nombre:");

        nombreDeUsuarioL.setText("Nombre de usuario:");

        contrasenaL.setText("Contraseña:");

        confirmarContrasenaL.setText("Confirmar contraseña:");

        correoL.setText("Correo:");

        rolL.setText("Rol:");

        rolCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Consulta", "Otro rol" }));

        cancelarB1.setText("Cancelar");

        modificarB1.setText("Modificar");

        org.jdesktop.layout.GroupLayout ModificarFLayout = new org.jdesktop.layout.GroupLayout(ModificarF.getContentPane());
        ModificarF.getContentPane().setLayout(ModificarFLayout);
        ModificarFLayout.setHorizontalGroup(
            ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelInfP1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(ModificarFLayout.createSequentialGroup()
                .add(15, 15, 15)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ModificarFLayout.createSequentialGroup()
                        .add(66, 66, 66)
                        .add(cancelarB1)
                        .add(18, 18, 18)
                        .add(modificarB1)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(ModificarFLayout.createSequentialGroup()
                        .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(ModificarFLayout.createSequentialGroup()
                                .add(nombreDeUsuarioL)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(nombreDeUsuarioTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(ModificarFLayout.createSequentialGroup()
                                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(contrasenaL)
                                    .add(confirmarContrasenaL)
                                    .add(rolL))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(correoTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, confirmarContrasenaPF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, contrasenaPF))
                                    .add(rolCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(ModificarFLayout.createSequentialGroup()
                                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(nombreL)
                                    .add(dniL)
                                    .add(correoL))
                                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ModificarFLayout.createSequentialGroup()
                                        .add(0, 0, Short.MAX_VALUE)
                                        .add(dniTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ModificarFLayout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(nombreTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                        .add(22, 22, 22))))
        );
        ModificarFLayout.setVerticalGroup(
            ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ModificarFLayout.createSequentialGroup()
                .add(panelSupP1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dniL)
                    .add(dniTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreL)
                    .add(nombreTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreDeUsuarioL)
                    .add(nombreDeUsuarioTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(contrasenaL)
                    .add(contrasenaPF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(confirmarContrasenaL)
                    .add(confirmarContrasenaPF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(correoL)
                    .add(correoTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rolL)
                    .add(rolCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(ModificarFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB1)
                    .add(modificarB1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelInfP1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        modificarUsuarioL.setText("SIAC - Modificar Usuario");
        panelSupP.add(modificarUsuarioL);
        modificarUsuarioL.setBounds(6, 7, 170, 16);

        bienvenidoL.setText("Buscar por:");

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        dniRB.setText("DNI");

        busquedaBG.add(nombreRB);
        nombreRB.setText("Nombre");

        buscarTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        buscarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buscarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        buscarB.setText("Buscar");

        usuarioT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Correo", "Rol", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usuarioSP.setViewportView(usuarioT);

        cancelarB.setText("Cancelar");

        modificarB.setText("Modificar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cancelarB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(modificarB))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(dniRB)
                                .add(18, 18, 18)
                                .add(nombreRB))
                            .add(bienvenidoL)
                            .add(layout.createSequentialGroup()
                                .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(buscarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(usuarioSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 520, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bienvenidoL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dniRB)
                    .add(nombreRB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(usuarioSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB)
                    .add(modificarB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ModificarF;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JToggleButton buscarB;
    private javax.swing.JTextField buscarTF;
    private javax.swing.ButtonGroup busquedaBG;
    private javax.swing.JButton cancelarB;
    private javax.swing.JButton cancelarB1;
    private javax.swing.JLabel confirmarContrasenaL;
    private javax.swing.JPasswordField confirmarContrasenaPF;
    private javax.swing.JLabel contrasenaL;
    private javax.swing.JPasswordField contrasenaPF;
    private javax.swing.JLabel correoL;
    private javax.swing.JTextField correoTF;
    private javax.swing.JLabel dniL;
    private javax.swing.JRadioButton dniRB;
    private javax.swing.JTextField dniTF;
    private javax.swing.JButton modificarB;
    private javax.swing.JButton modificarB1;
    private javax.swing.JLabel modificarUsuarioL;
    private javax.swing.JLabel modificarUsuarioL1;
    private javax.swing.JLabel nombreDeUsuarioL;
    private javax.swing.JTextField nombreDeUsuarioTF;
    private javax.swing.JLabel nombreL;
    private javax.swing.JRadioButton nombreRB;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelInfP1;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JPanel panelSupP1;
    private javax.swing.JComboBox rolCB;
    private javax.swing.JLabel rolL;
    private javax.swing.JScrollPane usuarioSP;
    private javax.swing.JTable usuarioT;
    // End of variables declaration//GEN-END:variables
}
