/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ModificarEmpresaController;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Felipe
 */
public class ModificarEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public ModificarEmpresa() {
        initComponents();
    }

    public JTable getEmpresaT() {
        return empresaT;
    }

    public JTextField getBuscarTF() {
        return buscarTF;
    }

    public JRadioButton getNitRB() {
        return nitRB;
    }

    public JTextField getDireccionTF() {
        return direccionTF;
    }

    public JTextField getNitTF() {
        return nitTF;
    }

    public JTextField getNivelTF() {
        return nivelTF;
    }

    public JTextField getNombreEmpresaTF() {
        return nombreEmpresaTF;
    }

    public JTextField getTelefonoTF() {
        return telefonoTF;
    }

    public JPanel getModificarEmpresaP() {
        return modificarEmpresaP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaBG = new javax.swing.ButtonGroup();
        modificarEmpresaP = new javax.swing.JPanel();
        nivelL = new javax.swing.JLabel();
        direccionL = new javax.swing.JLabel();
        telefonoL = new javax.swing.JLabel();
        nivelTF = new javax.swing.JTextField();
        cancelarB1 = new javax.swing.JButton();
        direccionTF = new javax.swing.JTextField();
        modificarEmpresaB = new javax.swing.JButton();
        nitTF = new javax.swing.JTextField();
        nitL = new javax.swing.JLabel();
        nombreEmpresaTF = new javax.swing.JTextField();
        nombreEmpresaL = new javax.swing.JLabel();
        telefonoTF = new javax.swing.JTextField();
        empresaL = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        nitRB = new javax.swing.JRadioButton();
        nombreRB = new javax.swing.JRadioButton();
        buscarTF = new javax.swing.JTextField();
        empresaSP = new javax.swing.JScrollPane();
        empresaT = new javax.swing.JTable();
        cancelarB = new javax.swing.JButton();
        modificarB = new javax.swing.JButton();
        buscarB = new javax.swing.JButton();

        nivelL.setText("Nivel:");

        direccionL.setText("Dirección:");

        telefonoL.setText("Teléfono:");

        nivelTF.setEditable(false);
        nivelTF.setText("Nivel");

        cancelarB1.setText("Cancelar");
        cancelarB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarB1ActionPerformed(evt);
            }
        });

        modificarEmpresaB.setText("Modificar Empresa");
        modificarEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpresaBActionPerformed(evt);
            }
        });

        nitTF.setEditable(false);

        nitL.setText("NIT: ");

        nombreEmpresaL.setText("Nombre:");

        empresaL.setText("Empresa:");

        org.jdesktop.layout.GroupLayout modificarEmpresaPLayout = new org.jdesktop.layout.GroupLayout(modificarEmpresaP);
        modificarEmpresaP.setLayout(modificarEmpresaPLayout);
        modificarEmpresaPLayout.setHorizontalGroup(
            modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(modificarEmpresaPLayout.createSequentialGroup()
                .addContainerGap()
                .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(modificarEmpresaPLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(telefonoL)
                            .add(nombreEmpresaL)
                            .add(nitL)
                            .add(nivelL)
                            .add(direccionL))
                        .add(27, 27, 27)
                        .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nombreEmpresaTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nitTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nivelTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(direccionTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(telefonoTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(empresaL)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, modificarEmpresaPLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cancelarB1)
                        .add(18, 18, 18)
                        .add(modificarEmpresaB)
                        .add(14, 14, 14)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modificarEmpresaPLayout.setVerticalGroup(
            modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(modificarEmpresaPLayout.createSequentialGroup()
                .addContainerGap()
                .add(empresaL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nitL)
                    .add(nitTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreEmpresaL)
                    .add(nombreEmpresaTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nivelL)
                    .add(nivelTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(direccionL)
                    .add(direccionTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(telefonoL)
                    .add(telefonoTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(modificarEmpresaPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB1)
                    .add(modificarEmpresaB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bienvenidoL.setText("Buscar por:");

        busquedaBG.add(nitRB);
        nitRB.setSelected(true);
        nitRB.setText("NIT");

        busquedaBG.add(nombreRB);
        nombreRB.setText("Nombre");

        buscarTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        empresaT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIT", "Nombre", "Nivel", "Dirección", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empresaSP.setViewportView(empresaT);

        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });

        modificarB.setText("Modificar");
        modificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBActionPerformed(evt);
            }
        });

        buscarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        buscarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        buscarB.setText("Buscar");
        buscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(modificarB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelarB))
                    .add(bienvenidoL)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(nitRB)
                                    .add(18, 18, 18)
                                    .add(nombreRB)
                                    .add(0, 0, Short.MAX_VALUE))
                                .add(buscarTF))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(buscarB))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, empresaSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 520, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(bienvenidoL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nitRB)
                    .add(nombreRB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buscarTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(empresaSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB)
                    .add(modificarB))
                .add(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarB1ActionPerformed
        new ModificarEmpresaController().listarEmpresa();
    }//GEN-LAST:event_cancelarB1ActionPerformed

    private void modificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBActionPerformed
        new ModificarEmpresaController().mostrarEmpresaEditable();
    }//GEN-LAST:event_modificarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        new ModificarEmpresaController().cancelar();
    }//GEN-LAST:event_cancelarBActionPerformed

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
        new ModificarEmpresaController().buscar();
    }//GEN-LAST:event_buscarBActionPerformed

    private void modificarEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpresaBActionPerformed
        new ModificarEmpresaController().modificarEmpresa();
    }//GEN-LAST:event_modificarEmpresaBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JButton buscarB;
    private javax.swing.JTextField buscarTF;
    private javax.swing.ButtonGroup busquedaBG;
    private javax.swing.JButton cancelarB;
    private javax.swing.JButton cancelarB1;
    private javax.swing.JLabel direccionL;
    private javax.swing.JTextField direccionTF;
    private javax.swing.JLabel empresaL;
    private javax.swing.JScrollPane empresaSP;
    private javax.swing.JTable empresaT;
    private javax.swing.JButton modificarB;
    private javax.swing.JButton modificarEmpresaB;
    private javax.swing.JPanel modificarEmpresaP;
    private javax.swing.JLabel nitL;
    private javax.swing.JRadioButton nitRB;
    private javax.swing.JTextField nitTF;
    private javax.swing.JLabel nivelL;
    private javax.swing.JTextField nivelTF;
    private javax.swing.JLabel nombreEmpresaL;
    private javax.swing.JTextField nombreEmpresaTF;
    private javax.swing.JRadioButton nombreRB;
    private javax.swing.JLabel telefonoL;
    private javax.swing.JTextField telefonoTF;
    // End of variables declaration//GEN-END:variables
}
