/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;

/**
 *
 * @author Felipe
 */
public class OtroRolPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public OtroRolPrincipal() {
        initComponents();
    }
    
    public JLabel getNombreEmpresaL() {
        return nombreEmpresaL;
    }

    public JLabel getNombreUsuarioL() {
        return nombreUsuarioL;
    }

    public JLabel getRolL() {
        return rolL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSupP = new javax.swing.JPanel();
        AdministradorL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelInfP = new javax.swing.JPanel();
        bienvenidoL = new javax.swing.JLabel();
        nombreUsuarioL = new javax.swing.JLabel();
        registradoL = new javax.swing.JLabel();
        nombreEmpresaL = new javax.swing.JLabel();
        rolLabelL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        AdministradorL.setText("SIAC - Usuario");
        panelSupP.add(AdministradorL);
        AdministradorL.setBounds(6, 7, 70, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User.png"))); // NOI18N

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        bienvenidoL.setText("Bienvenido de nuevo: ");

        nombreUsuarioL.setText("Administrador de TI");

        registradoL.setText("Esta registrado en la empresa: ");

        nombreEmpresaL.setText("UnalSoft S.A.S.");

        rolLabelL.setText("Su rol en esta empresa es: ");

        rolL.setText("Proveedor de TI");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(44, 44, 44)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(registradoL)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(nombreEmpresaL))
                    .add(layout.createSequentialGroup()
                        .add(rolLabelL)
                        .add(18, 18, 18)
                        .add(rolL))
                    .add(layout.createSequentialGroup()
                        .add(bienvenidoL)
                        .add(18, 18, 18)
                        .add(nombreUsuarioL)))
                .add(28, 28, 28))
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(bienvenidoL)
                            .add(nombreUsuarioL))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(registradoL)
                            .add(nombreEmpresaL))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(rolLabelL)
                            .add(rolL))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministradorL;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombreEmpresaL;
    private javax.swing.JLabel nombreUsuarioL;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JLabel registradoL;
    private javax.swing.JLabel rolL;
    private javax.swing.JLabel rolLabelL;
    // End of variables declaration//GEN-END:variables
}
