/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felipe
 */
public class PrimerAdministradorPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form AdministradorPrincipal
     */
    public PrimerAdministradorPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSupP = new javax.swing.JPanel();
        AdministradorL = new javax.swing.JLabel();
        cerrarB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        registradoL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();
        accionesL = new javax.swing.JLabel();
        administrarUsuariosP = new javax.swing.JPanel();
        crearUsuarioB = new javax.swing.JButton();
        consultarUsuarioB = new javax.swing.JButton();
        modificarUsuarioB = new javax.swing.JButton();
        eliminarUsuarioB = new javax.swing.JButton();
        administrarPrimerAdminP = new javax.swing.JPanel();
        crearPrimerAdminB = new javax.swing.JButton();
        consultarPrimerAdminB = new javax.swing.JButton();
        modificarPrimerAdminB = new javax.swing.JButton();
        eliminarPrimerAdminB = new javax.swing.JButton();
        administrarNivelP = new javax.swing.JPanel();
        crearEmpresaB = new javax.swing.JButton();
        consultarEmpresaB = new javax.swing.JButton();
        modificarEmpresaB = new javax.swing.JButton();
        eliminarEmpresaB = new javax.swing.JButton();
        panelInfP = new javax.swing.JPanel();

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        AdministradorL.setText("SIAC - Primer Administrador");
        panelSupP.add(AdministradorL);
        AdministradorL.setBounds(6, 7, 179, 16);

        cerrarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cerrarB.setText("X");
        cerrarB.setBorderPainted(false);
        cerrarB.setContentAreaFilled(false);
        cerrarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cerrarB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelSupP.add(cerrarB);
        cerrarB.setBounds(620, 0, 55, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User.png"))); // NOI18N

        bienvenidoL.setText("Bienvenido de nuevo: Primer Administrador");

        registradoL.setText("Esta registrado en la empresa: Empresa");

        rolL.setText("Su rol en esta empresa es: Primer Administrador");

        accionesL.setText("Las acciones que puede realizar son:");

        administrarUsuariosP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Usuarios de Empresa"));

        crearUsuarioB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearUsuarioB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Crear.png"))); // NOI18N
        crearUsuarioB.setText("Crear");
        crearUsuarioB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        consultarUsuarioB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarUsuarioB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarUsuarioB.setText("Consultar");
        consultarUsuarioB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        modificarUsuarioB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarUsuarioB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarUsuarioB.setText("Modificar");
        modificarUsuarioB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        eliminarUsuarioB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarUsuarioB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarUsuarioB.setText("Eliminar");
        eliminarUsuarioB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout administrarUsuariosPLayout = new org.jdesktop.layout.GroupLayout(administrarUsuariosP);
        administrarUsuariosP.setLayout(administrarUsuariosPLayout);
        administrarUsuariosPLayout.setHorizontalGroup(
            administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarUsuariosPLayout.createSequentialGroup()
                .addContainerGap()
                .add(administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(administrarUsuariosPLayout.createSequentialGroup()
                        .add(modificarUsuarioB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(eliminarUsuarioB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(38, 38, 38))
                    .add(administrarUsuariosPLayout.createSequentialGroup()
                        .add(crearUsuarioB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(consultarUsuarioB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        administrarUsuariosPLayout.setVerticalGroup(
            administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarUsuariosPLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crearUsuarioB)
                    .add(consultarUsuarioB))
                .add(30, 30, 30)
                .add(administrarUsuariosPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarUsuarioB)
                    .add(eliminarUsuarioB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        administrarPrimerAdminP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Primer Administrador de Nivel"));

        crearPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Crear.png"))); // NOI18N
        crearPrimerAdminB.setText("Crear");
        crearPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        consultarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarPrimerAdminB.setText("Consultar");
        consultarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        modificarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarPrimerAdminB.setText("Modificar");
        modificarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        eliminarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarPrimerAdminB.setText("Eliminar");
        eliminarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout administrarPrimerAdminPLayout = new org.jdesktop.layout.GroupLayout(administrarPrimerAdminP);
        administrarPrimerAdminP.setLayout(administrarPrimerAdminPLayout);
        administrarPrimerAdminPLayout.setHorizontalGroup(
            administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .addContainerGap()
                .add(administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(administrarPrimerAdminPLayout.createSequentialGroup()
                        .add(modificarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(eliminarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(38, 38, 38))
                    .add(administrarPrimerAdminPLayout.createSequentialGroup()
                        .add(crearPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(consultarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        administrarPrimerAdminPLayout.setVerticalGroup(
            administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crearPrimerAdminB)
                    .add(consultarPrimerAdminB))
                .add(30, 30, 30)
                .add(administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarPrimerAdminB)
                    .add(eliminarPrimerAdminB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        administrarNivelP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Nivel"));

        crearEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Crear.png"))); // NOI18N
        crearEmpresaB.setText("Crear");
        crearEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        consultarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarEmpresaB.setText("Consultar");
        consultarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        modificarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarEmpresaB.setText("Modificar");
        modificarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        eliminarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarEmpresaB.setText("Eliminar");
        eliminarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout administrarNivelPLayout = new org.jdesktop.layout.GroupLayout(administrarNivelP);
        administrarNivelP.setLayout(administrarNivelPLayout);
        administrarNivelPLayout.setHorizontalGroup(
            administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarNivelPLayout.createSequentialGroup()
                .addContainerGap()
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(administrarNivelPLayout.createSequentialGroup()
                        .add(modificarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(eliminarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(38, 38, 38))
                    .add(administrarNivelPLayout.createSequentialGroup()
                        .add(crearEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(consultarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        administrarNivelPLayout.setVerticalGroup(
            administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarNivelPLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crearEmpresaB)
                    .add(consultarEmpresaB))
                .add(30, 30, 30)
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarEmpresaB)
                    .add(eliminarEmpresaB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jLabel2)
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, registradoL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bienvenidoL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, rolL)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(accionesL)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(administrarNivelP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(administrarPrimerAdminP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(administrarUsuariosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(bienvenidoL)
                        .add(18, 18, 18)
                        .add(registradoL)
                        .add(18, 18, 18)
                        .add(rolL)))
                .add(29, 29, 29)
                .add(accionesL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(administrarPrimerAdminP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(administrarNivelP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(administrarUsuariosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministradorL;
    private javax.swing.JLabel accionesL;
    private javax.swing.JPanel administrarNivelP;
    private javax.swing.JPanel administrarPrimerAdminP;
    private javax.swing.JPanel administrarUsuariosP;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JButton cerrarB;
    private javax.swing.JButton consultarEmpresaB;
    private javax.swing.JButton consultarPrimerAdminB;
    private javax.swing.JButton consultarUsuarioB;
    private javax.swing.JButton crearEmpresaB;
    private javax.swing.JButton crearPrimerAdminB;
    private javax.swing.JButton crearUsuarioB;
    private javax.swing.JButton eliminarEmpresaB;
    private javax.swing.JButton eliminarPrimerAdminB;
    private javax.swing.JButton eliminarUsuarioB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton modificarEmpresaB;
    private javax.swing.JButton modificarPrimerAdminB;
    private javax.swing.JButton modificarUsuarioB;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JLabel registradoL;
    private javax.swing.JLabel rolL;
    // End of variables declaration//GEN-END:variables
}
