/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConsultarAdministradorController;
import controller.LoginController;
import controller.ProveedorTIPrincipalController;
import javax.swing.JLabel;

/**
 *
 * @author Felipe
 */
public class ProveedorTIPrincipal extends javax.swing.JPanel {
    
    ProveedorTIPrincipalController controller =  new ProveedorTIPrincipalController();

    /**
     * Creates new form AdministradorPrincipal
     */
    public ProveedorTIPrincipal() {
        initComponents();
    }

    public JLabel getNombreEmpresaL() {
        return nombreEmpresaL;
    }

    public JLabel getNombreUsuarioL() {
        return nombreUsuarioL;
    }

    public JLabel getRolL() {
        return rolL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        registradoL = new javax.swing.JLabel();
        rolLabelL = new javax.swing.JLabel();
        accionesL = new javax.swing.JLabel();
        mantenimientoP = new javax.swing.JPanel();
        crearCopiaDeSeguridadB = new javax.swing.JButton();
        restablecerCopiaDeSeguridadB = new javax.swing.JButton();
        administrarPrimerAdminP = new javax.swing.JPanel();
        consultarPrimerAdminB = new javax.swing.JButton();
        modificarPrimerAdminB = new javax.swing.JButton();
        eliminarPrimerAdminB = new javax.swing.JButton();
        administrarNivelP = new javax.swing.JPanel();
        crearEmpresaB = new javax.swing.JButton();
        consultarEmpresaB = new javax.swing.JButton();
        modificarEmpresaB = new javax.swing.JButton();
        eliminarEmpresaB = new javax.swing.JButton();
        nombreUsuarioL = new javax.swing.JLabel();
        nombreEmpresaL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();
        cerrarSesionB = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User.png"))); // NOI18N

        bienvenidoL.setText("Bienvenido de nuevo: ");

        registradoL.setText("Esta registrado en la empresa: ");

        rolLabelL.setText("Su rol en esta empresa es: ");

        accionesL.setText("Las acciones que puede realizar son:");

        mantenimientoP.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));

        crearCopiaDeSeguridadB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearCopiaDeSeguridadB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Backup.png"))); // NOI18N
        crearCopiaDeSeguridadB.setText("Crear copia de seguridad");
        crearCopiaDeSeguridadB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearCopiaDeSeguridadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCopiaDeSeguridadBActionPerformed(evt);
            }
        });

        restablecerCopiaDeSeguridadB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        restablecerCopiaDeSeguridadB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Resaturar.png"))); // NOI18N
        restablecerCopiaDeSeguridadB.setText("Restablecer copia de seguridad");
        restablecerCopiaDeSeguridadB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        restablecerCopiaDeSeguridadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restablecerCopiaDeSeguridadBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout mantenimientoPLayout = new org.jdesktop.layout.GroupLayout(mantenimientoP);
        mantenimientoP.setLayout(mantenimientoPLayout);
        mantenimientoPLayout.setHorizontalGroup(
            mantenimientoPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mantenimientoPLayout.createSequentialGroup()
                .addContainerGap()
                .add(mantenimientoPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(restablecerCopiaDeSeguridadB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(crearCopiaDeSeguridadB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mantenimientoPLayout.setVerticalGroup(
            mantenimientoPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mantenimientoPLayout.createSequentialGroup()
                .addContainerGap()
                .add(crearCopiaDeSeguridadB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(restablecerCopiaDeSeguridadB)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        administrarPrimerAdminP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Primer Administrador de Distribuidores"));

        consultarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarPrimerAdminB.setText("Consultar");
        consultarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consultarPrimerAdminB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPrimerAdminBActionPerformed(evt);
            }
        });

        modificarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarPrimerAdminB.setText("Modificar");
        modificarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        modificarPrimerAdminB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPrimerAdminBActionPerformed(evt);
            }
        });

        eliminarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarPrimerAdminB.setText("Eliminar");
        eliminarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eliminarPrimerAdminB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPrimerAdminBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout administrarPrimerAdminPLayout = new org.jdesktop.layout.GroupLayout(administrarPrimerAdminP);
        administrarPrimerAdminP.setLayout(administrarPrimerAdminPLayout);
        administrarPrimerAdminPLayout.setHorizontalGroup(
            administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .addContainerGap()
                .add(modificarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 41, Short.MAX_VALUE)
                .add(eliminarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .add(95, 95, 95)
                .add(consultarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        administrarPrimerAdminPLayout.setVerticalGroup(
            administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(consultarPrimerAdminB)
                .add(26, 26, 26)
                .add(administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarPrimerAdminB)
                    .add(eliminarPrimerAdminB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        administrarNivelP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Distribuidores"));

        crearEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Crear.png"))); // NOI18N
        crearEmpresaB.setText("Crear");
        crearEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEmpresaBActionPerformed(evt);
            }
        });

        consultarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarEmpresaB.setText("Consultar");
        consultarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consultarEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEmpresaBActionPerformed(evt);
            }
        });

        modificarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarEmpresaB.setText("Modificar");
        modificarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        modificarEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpresaBActionPerformed(evt);
            }
        });

        eliminarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarEmpresaB.setText("Eliminar");
        eliminarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eliminarEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpresaBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout administrarNivelPLayout = new org.jdesktop.layout.GroupLayout(administrarNivelP);
        administrarNivelP.setLayout(administrarNivelPLayout);
        administrarNivelPLayout.setHorizontalGroup(
            administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarNivelPLayout.createSequentialGroup()
                .addContainerGap()
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(administrarNivelPLayout.createSequentialGroup()
                        .add(modificarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(eliminarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(38, 38, 38))
                    .add(administrarNivelPLayout.createSequentialGroup()
                        .add(crearEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(consultarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        administrarNivelPLayout.setVerticalGroup(
            administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarNivelPLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crearEmpresaB)
                    .add(consultarEmpresaB))
                .add(30, 30, 30)
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarEmpresaB)
                    .add(eliminarEmpresaB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nombreUsuarioL.setText("Administrador de TI");

        nombreEmpresaL.setText("UnalSoft S.A.S.");

        rolL.setText("Proveedor de TI");

        cerrarSesionB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CerrarSesion.png"))); // NOI18N
        cerrarSesionB.setText("Cerrar sesión");
        cerrarSesionB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrarSesionB.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cerrarSesionB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrarSesionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(accionesL)
                            .add(layout.createSequentialGroup()
                                .add(174, 174, 174)
                                .add(mantenimientoP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(jLabel2)
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(rolLabelL)
                                        .add(18, 18, 18)
                                        .add(rolL))
                                    .add(layout.createSequentialGroup()
                                        .add(registradoL)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(nombreEmpresaL)))
                                .addContainerGap())
                            .add(layout.createSequentialGroup()
                                .add(bienvenidoL)
                                .add(18, 18, 18)
                                .add(nombreUsuarioL)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(cerrarSesionB))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(administrarNivelP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(administrarPrimerAdminP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel2)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(bienvenidoL)
                                    .add(nombreUsuarioL))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(registradoL)
                                    .add(nombreEmpresaL))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(rolLabelL)
                                    .add(rolL)))))
                    .add(cerrarSesionB))
                .add(31, 31, 31)
                .add(accionesL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(administrarPrimerAdminP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(administrarNivelP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(mantenimientoP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEmpresaBActionPerformed
        controller.crearEmpresa();
    }//GEN-LAST:event_crearEmpresaBActionPerformed

    private void consultarEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEmpresaBActionPerformed
        controller.consultarEmpresa();
    }//GEN-LAST:event_consultarEmpresaBActionPerformed

    private void modificarEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpresaBActionPerformed
        controller.modificarEmpresa();
    }//GEN-LAST:event_modificarEmpresaBActionPerformed

    private void eliminarEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpresaBActionPerformed
        controller.eliminarEmpresa();
    }//GEN-LAST:event_eliminarEmpresaBActionPerformed

    private void consultarPrimerAdminBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPrimerAdminBActionPerformed
        new ConsultarAdministradorController().consultarUsuario();
    }//GEN-LAST:event_consultarPrimerAdminBActionPerformed

    private void modificarPrimerAdminBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPrimerAdminBActionPerformed
        //controller.modificarAdministrador();
    }//GEN-LAST:event_modificarPrimerAdminBActionPerformed

    private void eliminarPrimerAdminBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPrimerAdminBActionPerformed
        //controller.eliminarAdministrador();
    }//GEN-LAST:event_eliminarPrimerAdminBActionPerformed

    private void cerrarSesionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBActionPerformed
        LoginController.cerrarSesion();
    }//GEN-LAST:event_cerrarSesionBActionPerformed

    private void crearCopiaDeSeguridadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCopiaDeSeguridadBActionPerformed
        controller.crearCopiaDeSeguridad();
    }//GEN-LAST:event_crearCopiaDeSeguridadBActionPerformed

    private void restablecerCopiaDeSeguridadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restablecerCopiaDeSeguridadBActionPerformed
        controller.restablecerCopiaDeSeguridad();
    }//GEN-LAST:event_restablecerCopiaDeSeguridadBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accionesL;
    private javax.swing.JPanel administrarNivelP;
    private javax.swing.JPanel administrarPrimerAdminP;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JButton cerrarSesionB;
    private javax.swing.JButton consultarEmpresaB;
    private javax.swing.JButton consultarPrimerAdminB;
    private javax.swing.JButton crearCopiaDeSeguridadB;
    private javax.swing.JButton crearEmpresaB;
    private javax.swing.JButton eliminarEmpresaB;
    private javax.swing.JButton eliminarPrimerAdminB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mantenimientoP;
    private javax.swing.JButton modificarEmpresaB;
    private javax.swing.JButton modificarPrimerAdminB;
    private javax.swing.JLabel nombreEmpresaL;
    private javax.swing.JLabel nombreUsuarioL;
    private javax.swing.JLabel registradoL;
    private javax.swing.JButton restablecerCopiaDeSeguridadB;
    private javax.swing.JLabel rolL;
    private javax.swing.JLabel rolLabelL;
    // End of variables declaration//GEN-END:variables
}
