/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProveedorTIPrincipalController;

/**
 *
 * @author Felipe
 */
public class ProveedorTIPrincipal extends javax.swing.JPanel {
    
    ProveedorTIPrincipalController controller =  new ProveedorTIPrincipalController();

    /**
     * Creates new form AdministradorPrincipal
     */
    public ProveedorTIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSupP = new javax.swing.JPanel();
        ProveedorTIL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bienvenidoL = new javax.swing.JLabel();
        registradoL = new javax.swing.JLabel();
        rolL = new javax.swing.JLabel();
        accionesL = new javax.swing.JLabel();
        mantenimientoP = new javax.swing.JPanel();
        crearCopiaDeSeguridadB = new javax.swing.JButton();
        restablecerCopiaDeSeguridadB = new javax.swing.JButton();
        administrarPrimerAdminP = new javax.swing.JPanel();
        consultarPrimerAdminB = new javax.swing.JButton();
        modificarPrimerAdminB = new javax.swing.JButton();
        eliminarPrimerAdminB = new javax.swing.JButton();
        administrarNivelP = new javax.swing.JPanel();
        crearEmpresaB = new javax.swing.JButton();
        consultarEmpresaB = new javax.swing.JButton();
        modificarEmpresaB = new javax.swing.JButton();
        eliminarEmpresaB = new javax.swing.JButton();
        panelInfP = new javax.swing.JPanel();

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        ProveedorTIL.setText("IAC - Proveedor de TI");
        panelSupP.add(ProveedorTIL);
        ProveedorTIL.setBounds(6, 7, 106, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User.png"))); // NOI18N

        bienvenidoL.setText("Bienvenido de nuevo: Administrador de TI");

        registradoL.setText("Esta registrado en la empresa: UnalSoft S.A.S.");

        rolL.setText("Su rol en esta empresa es: Proveedor de TI");

        accionesL.setText("Las acciones que puede realizar son:");

        mantenimientoP.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));

        crearCopiaDeSeguridadB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearCopiaDeSeguridadB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Backup.png"))); // NOI18N
        crearCopiaDeSeguridadB.setText("Crear copia de seguridad");
        crearCopiaDeSeguridadB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        restablecerCopiaDeSeguridadB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        restablecerCopiaDeSeguridadB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Resaturar.png"))); // NOI18N
        restablecerCopiaDeSeguridadB.setText("Restablecer copia de seguridad");
        restablecerCopiaDeSeguridadB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout mantenimientoPLayout = new org.jdesktop.layout.GroupLayout(mantenimientoP);
        mantenimientoP.setLayout(mantenimientoPLayout);
        mantenimientoPLayout.setHorizontalGroup(
            mantenimientoPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mantenimientoPLayout.createSequentialGroup()
                .addContainerGap()
                .add(mantenimientoPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(restablecerCopiaDeSeguridadB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(crearCopiaDeSeguridadB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mantenimientoPLayout.setVerticalGroup(
            mantenimientoPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mantenimientoPLayout.createSequentialGroup()
                .addContainerGap()
                .add(crearCopiaDeSeguridadB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(restablecerCopiaDeSeguridadB)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        administrarPrimerAdminP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Primer Administrador de Distribuidores"));

        consultarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarPrimerAdminB.setText("Consultar");
        consultarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        modificarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarPrimerAdminB.setText("Modificar");
        modificarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        eliminarPrimerAdminB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarPrimerAdminB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarPrimerAdminB.setText("Eliminar");
        eliminarPrimerAdminB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout administrarPrimerAdminPLayout = new org.jdesktop.layout.GroupLayout(administrarPrimerAdminP);
        administrarPrimerAdminP.setLayout(administrarPrimerAdminPLayout);
        administrarPrimerAdminPLayout.setHorizontalGroup(
            administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .addContainerGap()
                .add(modificarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(eliminarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .add(95, 95, 95)
                .add(consultarPrimerAdminB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        administrarPrimerAdminPLayout.setVerticalGroup(
            administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarPrimerAdminPLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(consultarPrimerAdminB)
                .add(26, 26, 26)
                .add(administrarPrimerAdminPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarPrimerAdminB)
                    .add(eliminarPrimerAdminB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        administrarNivelP.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Distribuidores"));

        crearEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        crearEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Crear.png"))); // NOI18N
        crearEmpresaB.setText("Crear");
        crearEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEmpresaBActionPerformed(evt);
            }
        });

        consultarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Consultar.png"))); // NOI18N
        consultarEmpresaB.setText("Consultar");
        consultarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consultarEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEmpresaBActionPerformed(evt);
            }
        });

        modificarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modificarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Modificar.png"))); // NOI18N
        modificarEmpresaB.setText("Modificar");
        modificarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        modificarEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpresaBActionPerformed(evt);
            }
        });

        eliminarEmpresaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eliminarEmpresaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Eliminar.png"))); // NOI18N
        eliminarEmpresaB.setText("Eliminar");
        eliminarEmpresaB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eliminarEmpresaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpresaBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout administrarNivelPLayout = new org.jdesktop.layout.GroupLayout(administrarNivelP);
        administrarNivelP.setLayout(administrarNivelPLayout);
        administrarNivelPLayout.setHorizontalGroup(
            administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarNivelPLayout.createSequentialGroup()
                .addContainerGap()
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(administrarNivelPLayout.createSequentialGroup()
                        .add(modificarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(eliminarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(38, 38, 38))
                    .add(administrarNivelPLayout.createSequentialGroup()
                        .add(crearEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(consultarEmpresaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        administrarNivelPLayout.setVerticalGroup(
            administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(administrarNivelPLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(crearEmpresaB)
                    .add(consultarEmpresaB))
                .add(30, 30, 30)
                .add(administrarNivelPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(modificarEmpresaB)
                    .add(eliminarEmpresaB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));
        panelInfP.setLayout(null);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(administrarNivelP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(administrarPrimerAdminP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(44, 44, 44)
                                .add(jLabel2)
                                .add(33, 33, 33)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, registradoL)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, bienvenidoL)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, rolL)))
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(accionesL)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(180, 180, 180)
                .add(mantenimientoP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(bienvenidoL)
                        .add(18, 18, 18)
                        .add(registradoL)
                        .add(18, 18, 18)
                        .add(rolL)))
                .add(29, 29, 29)
                .add(accionesL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(administrarPrimerAdminP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(administrarNivelP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(mantenimientoP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 21, Short.MAX_VALUE)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEmpresaBActionPerformed
        controller.crearEmpresa();
    }//GEN-LAST:event_crearEmpresaBActionPerformed

    private void consultarEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEmpresaBActionPerformed
        controller.consultarEmpresa();
    }//GEN-LAST:event_consultarEmpresaBActionPerformed

    private void modificarEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpresaBActionPerformed
        controller.modificarEmpresa();
    }//GEN-LAST:event_modificarEmpresaBActionPerformed

    private void eliminarEmpresaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpresaBActionPerformed
        controller.eliminarEmpresa();
    }//GEN-LAST:event_eliminarEmpresaBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProveedorTIL;
    private javax.swing.JLabel accionesL;
    private javax.swing.JPanel administrarNivelP;
    private javax.swing.JPanel administrarPrimerAdminP;
    private javax.swing.JLabel bienvenidoL;
    private javax.swing.JButton consultarEmpresaB;
    private javax.swing.JButton consultarPrimerAdminB;
    private javax.swing.JButton crearCopiaDeSeguridadB;
    private javax.swing.JButton crearEmpresaB;
    private javax.swing.JButton eliminarEmpresaB;
    private javax.swing.JButton eliminarPrimerAdminB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mantenimientoP;
    private javax.swing.JButton modificarEmpresaB;
    private javax.swing.JButton modificarPrimerAdminB;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JLabel registradoL;
    private javax.swing.JButton restablecerCopiaDeSeguridadB;
    private javax.swing.JLabel rolL;
    // End of variables declaration//GEN-END:variables
}
