/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RecuperarContrasenaController;

/**
 *
 * @author Felipe
 */
public class RecuperarContrasena extends javax.swing.JPanel {

    /**
     * Creates new form RecuperarContrasena
     */
    public RecuperarContrasena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSupP = new javax.swing.JPanel();
        restablecerContrasenaL = new javax.swing.JLabel();
        emailL = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        cancelarB = new javax.swing.JButton();
        restablecerContrasenaB = new javax.swing.JButton();
        panelInfP = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(397, 161));
        setMinimumSize(new java.awt.Dimension(397, 161));

        panelSupP.setBackground(new java.awt.Color(181, 181, 181));
        panelSupP.setLayout(null);

        restablecerContrasenaL.setText("SIAC - Restablecer Contraseña");
        panelSupP.add(restablecerContrasenaL);
        restablecerContrasenaL.setBounds(6, 7, 192, 16);

        emailL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emailL.setText("Email:");
        emailL.setToolTipText("");

        emailTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        cancelarB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });

        restablecerContrasenaB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        restablecerContrasenaB.setText("Restablecer Contraseña");

        panelInfP.setBackground(new java.awt.Color(181, 181, 181));

        org.jdesktop.layout.GroupLayout panelInfPLayout = new org.jdesktop.layout.GroupLayout(panelInfP);
        panelInfP.setLayout(panelInfPLayout);
        panelInfPLayout.setHorizontalGroup(
            panelInfPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        panelInfPLayout.setVerticalGroup(
            panelInfPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 18, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(panelSupP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .add(panelInfP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(cancelarB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(restablecerContrasenaB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(emailL)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(emailTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 261, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(panelSupP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailL)
                    .add(emailTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelarB)
                    .add(restablecerContrasenaB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelInfP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        RecuperarContrasenaController.mostrarLogin();
    }//GEN-LAST:event_cancelarBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JPanel panelInfP;
    private javax.swing.JPanel panelSupP;
    private javax.swing.JButton restablecerContrasenaB;
    private javax.swing.JLabel restablecerContrasenaL;
    // End of variables declaration//GEN-END:variables
}
