/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author Felipe
 */
public class Secundario extends javax.swing.JFrame {

    /**
     * Creates new form Secundario
     */
    public Secundario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        layoutP.setLayout(new java.awt.BorderLayout());
        getContentPane().add(layoutP);
        layoutP.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static JPanel getLayoutP() {
        return layoutP;
    }

    public static void setLayoutP(JPanel layoutP) {
        Secundario.layoutP = layoutP;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel layoutP;
    // End of variables declaration//GEN-END:variables
}
